# Generated by Django 5.2.5 on 2025-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_delivery_method_order_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lace_type',
            field=models.CharField(blank=True, choices=[('HD Lace', 'HD Lace'), ('Swiss Lace', 'Swiss Lace')], help_text='If this product is a lace, choose its lace type (HD Lace / Swiss Lace).', max_length=50, null=True),
        ),
    ]
