# Generated by Django 5.2.5 on 2025-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_color_product_color_options_product_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
