# Generated by Django 5.2.5 on 2025-11-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productimage_caption_productimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lace_type',
            field=models.CharField(blank=True, choices=[('HD Lace', 'HD Lace'), ('Swiss Lace', 'Swiss Lace'), ('Transparent Lace', 'Transparent Lace')], help_text='If this product is a lace, choose its lace type (HD Lace / Swiss Lace).', max_length=50, null=True),
        ),
    ]
