# Generated by Django 5.2.5 on 2025-10-06 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(blank=True, choices=[('shipping', 'Shipping & Delivery'), ('returns', 'Returns & Refunds'), ('payment', 'Payment & Checkout'), ('product', 'Product Info'), ('general', 'General')], help_text='Used to group related FAQs (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='opt_in',
            field=models.BooleanField(default=False, help_text='User explicitly consented to follow-up messages'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata (e.g. detected intent)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='memory',
            field=models.JSONField(blank=True, default=dict, help_text='Session memory (context during chat)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata (ip, user agent, utm, etc.)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated trigger words/phrases for rule-based matching'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, help_text='Source of lead (e.g. chat-widget)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category'], name='assistant_f_categor_440ca7_idx'),
        ),
    ]
