# Generated by Django 5.2.5 on 2025-10-20 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_chatsession_user_faq_category_lead_opt_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('requires_human', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unanswered_queries', to='assistant.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
