# Generated by Django 5.2.5 on 2025-10-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_unansweredquery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='requires_human',
            field=models.BooleanField(default=False, help_text='Marked if AI couldn’t answer or intent unclear'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='memory',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
