# Generated by Django 5.2.5 on 2025-10-20 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_chatmessage_requires_human_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='requires_human',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata (e.g. detected intent)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='memory',
            field=models.JSONField(blank=True, default=dict, help_text='Session memory (context during chat)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Optional metadata (ip, user agent, utm, etc.)'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
