# Generated by Django 5.2.5 on 2025-09-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(db_index=True, default='XX', max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(db_index=True, default='XXX', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postal_codes', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country', 'region')},
        ),
        migrations.AddIndex(
            model_name='postalcode',
            index=models.Index(fields=['code'], name='locations_p_code_abbc70_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['name'], name='locations_r_name_e5c9f5_idx'),
        ),
    ]
