# Generated by Django 5.2.5 on 2025-10-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_country_options_remove_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DHLAvailableCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dhl_info', to='locations.country')),
            ],
            options={
                'verbose_name_plural': 'DHL Available Countries',
            },
        ),
    ]
